[deps]
ComplexPlots = "1fd36721-02e5-4f31-ac70-029fcd7253d3"
ComplexRegions = "c64915e2-6c82-11e9-38e9-1f159a780463"
ComplexValues = "41a84b80-6cf2-11e9-379d-9df124847946"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
